{{- if eq ( .Values.enableNetworkPolicy | toString ) "yes" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingresscontroller
  namespace: {{ .Values.namespace | default "default" }}
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx   # These labels are specific to nginx-ingress controller only. If another ingress controller is used. New rule has to be created
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: ingress-nginx

  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: ingress-nginx

  policyTypes:
  - Egress
  - Ingress
{{- end }}
