{{- if eq ( .Values.enableNetworkPolicy | toString ) "yes" }}

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny-all
  namespace: {{ .Values.namespace | default "default" }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

{{- end }}
