{{- if eq ( .Values.enableNetworkPolicy | toString ) "yes" }}
{{- if eq ( .Values.enableKafka | toString) "yes" }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dextrus-allow-ingress-kafka
  namespace: {{ .Values.namespace | default "default" }}
spec:
  podSelector:
    matchLabels:
      netpol: kafka-communication
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          netpol: kafka

{{- end }}
{{- end }}
