{{- if eq ( .Values.enableNetworkPolicy | toString ) "yes" }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dextrus-allow-ingress-sparkexecutor
  namespace: {{ .Values.namespace | default "default" }}
spec:
  podSelector:
    matchLabels:
      netpol: kafka-communication
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          spark-role: executor

{{- end }}
