{{- if eq ( .Values.enableNetworkPolicy | toString ) "yes" }}
{{- if eq ( .Values.enableKafka | toString) "yes" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-allow-egress-dextrus
  namespace: {{ .Values.namespace | default "default" }}
spec:
  podSelector:
    matchLabels:
      netpol: kafka
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          netpol: kafka-communication
          
{{- end }}
{{- end }}
