#{{- if eq ( .Values.enableNetworkPolicy | toString ) "yes" }}
#{{- range $key, $val := .Values.networkPolicies }}
#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
#  name: {{ $val.app }}-allow-ingress-{{ $key }}
#  namespace: {{ $.Values.namespace | default "default" }}
#spec:
#  podSelector:
#    matchLabels:
#      app: {{ $val.app }}
#  policyTypes:
#  - Ingress
#  ingress:
#  - from:
#    - podSelectr:
#        matchLaels:
#          app: {{ $key }}
#    ports:
#    - protocol: TCP
#      port: {{ $val.port | quote }}
#
#{{- end }}
#{{- end }}
