apiVersion: v1
data:
  application.yml: |
    spring:
      profiles:
        active: dev
kind: ConfigMap
metadata:
  name: application-cm
  namespace: {{ .Values.namespace | default "default" }}
  resourceVersion: "42573296"
