apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbexplorer-deploy
  namespace: {{ .Values.namespace| default "default" }}
  labels:
    app: dbexplorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbexplorer
  template:
    metadata:
      labels:
        app: dbexplorer
    spec:
      containers:
        - name: dbexplorer
          image: {{ .Values.image.dbexplorerImage }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: efs-pvc
              mountPath: "/assets"
            - name: dextrus-config-maps
              mountPath: "/home/dbexplorer/resources/"
              readOnly: true
          command:
            - /bin/bash
            - -c
            - |
              cp /home/dbexplorer/resources/hive-site.xml ./
              cp /home/dbexplorer/resources/metastore-site.xml ./
              jar uf app.jar hive-site.xml metastore-site.xml
              java -jar app.jar --spring.config.location="/home/dbexplorer/resources/"
      volumes:
        - name: efs-pvc
          persistentVolumeClaim:
            claimName: efs
        - name: dextrus-config-maps
          projected:
            sources:
            - configMap:
                name: dbexplorer-appdev-cm
            - configMap:
                name: hive-site-cm
            - configMap:
                name: metastore-site-cm
            - configMap:
                name: application-cm

