apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-dextrusui-deploy
  namespace: {{ .Values.namespace | default "ClusterIP" }}
  labels:
    app: {{ .Values.name }}-dextrusui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-dextrusui
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-dextrusui
    spec:
      containers:
      - name: {{ .Values.name }}-dextrusui
        image: 157557265942.dkr.ecr.ap-south-1.amazonaws.com/dextrusui:cluster-0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
