kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}-efs-provisioner
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-efs-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-efs-provisioner
    spec:
      serviceAccount: {{ .Values.name }}-efs-provisioner
      containers:
        - name: {{ .Values.name }}-efs-provisioner
          image: quay.io/external_storage/efs-provisioner:latest
          env:
            - name: FILE_SYSTEM_ID
              value: {{ .Values.efs.fileSystemID }}
            - name: AWS_REGION
              value: {{ .Values.efs.region }}
            - name: DNS_NAME
              value: ""
            - name: PROVISIONER_NAME
              value: {{ .Values.name }}-efs-provisioner-name
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
      volumes:
        - name: pv-volume
          nfs:
            server: {{ .Values.efs.nfs.server }}
            path: /
