kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-efs-provisioner
  namespace: {{ .Values.namespace | default "default" }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-efs-provisioner
  namespace: {{ .Values.namespace | default "default" }}
subjects:
  - kind: ServiceAccount
    name: efs-provisioner
    namespace: {{ .Values.namespace | default "default" }}
roleRef:
  kind: Role
  name: leader-locking-efs-provisioner
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.namespace }}-efs-provisioner-runner
  namespace: {{ .Values.namespace | default "default" }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.namespace }}-run-efs-provisioner
  namespace: {{ .Values.namespace | default "default" }}
subjects:
  - kind: ServiceAccount
    name: efs-provisioner
    namespace: {{ .Values.namespace | default "default" }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.namespace }}-efs-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
