apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-streaming-deploy
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ .Values.name }}-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-streaming
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-streaming
    spec:
      containers:
      - name: streaming
        image: 157557265942.dkr.ecr.ap-south-1.amazonaws.com/streaming:cluster-0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
