apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-deploy
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: streaming
    netpol: kafka-communication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming
      netpol: kafka-communication
  template:
    metadata:
      labels:
        app: streaming
        netpol: kafka-communication
    spec:
      containers:
      - name: streaming
        image: {{ .Values.image.streamingImage }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
