apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysvar-deploy
  namespace: {{.Values.namespace | default "default" }}
  labels:
    app: sysvar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sysvar
  template:
    metadata:
      labels:
        app: sysvar
    spec:
      containers:
      - name: sysvar
        image: {{ .Values.image.systemvariablesImage }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: dextrus-config-maps
            mountPath: "/home/systemvariables/resources"
            readOnly: true

      volumes:
        - name: dextrus-config-maps
          projected:
            sources:
            - configMap:
                name: sysvar-appdev-cm
            - configMap:
                name: hive-site-cm
            - configMap:
                name: metastore-site-cm
            - configMap:
                name: application-cm

