apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-deploy
  namespace: {{ .Values.namespace | default "default"}}
  labels:
    app: twitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter
  template:
    metadata:
      labels:
        app: twitter
    spec:
      containers:
        - name: twitter
          image: {{ .Values.image.twitterImage }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: dextrus-config-maps
              mountPath: "/home/twitter/resources"
              readOnly: true
      volumes:
        - name: dextrus-config-maps
          projected:
            sources:
            - configMap:
                name: twitter-appdev-cm                    
            - configMap:
                name: application-cm

