---
{{- if eq .Values.installKafka "yes" }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zookeeper-pdb
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: zookeeper
    netpol: kafka

spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: zookeeper
      netpol: kafka
{{- else }}
{{- end }}
