# Default values for dextrus-application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


name: "test"
namespace: ""

s3:
  bucket_name: "dextrus-test28092021"
  access_key: "AKIASJLZFCYLLMLRSROS"
  secret_key: "165JnSLI35eW453adwxwtwf3SNJdCT2I0P5j6Kt7"
  region: "ap-south-1"

rds_end_point: "terraform-20210928143533128300000001.ciwmij2ca5ul.ap-south-1.rds.amazonaws.com" 
deploymentMode: "s3Cluster"

kubernetes:
  master: "https://21E8134B7861EB39271BAA762E942EA6.yl4.ap-south-1.eks.amazonaws.com"


efs:
  fileSystemID: "fs-0efa8a157be49c182"
  region: "ap-south-1"
  dnsName: ""
  nfs:
    server: "fs-0efa8a157be49c182.efs.ap-south-1.amazonaws.com"

dextrusui:
  service:
    type: ""

dextrusprod:
  service:
    type: ""


dextrusweb:
  spark_service:
    type: ""
  service:
    type: ""
  data:
    applicationDev:
      frontendUrl: "http://54.193.227.29:9090"
      logi:
        baseUrl: "http://3.127.245.90:8080"
        username: "supervisor"
        password: "Dextrus!123"

dbexplorer:
  service:
    type: ""
  spark_service:
    type: ""

wrangler:
  service:
    type: ""
  spark_service:
    type: ""

streaming:
  service:
    type: ""

systemVariable:
  service:
    type: ""

twitter:
  service:
    type: ""



  #replicaCount: 1
  #
  #image:
  #  repository: nginx
  #  pullPolicy: IfNotPresent
  #  # Overrides the image tag whose default is the chart appVersion.
  #  tag: ""
  #
  #imagePullSecrets: []
  #nameOverride: ""
  #fullnameOverride: ""
  #
  #serviceAccount:
  #  # Specifies whether a service account should be created
  #  create: true
  #  # Annotations to add to the service account
  #  annotations: {}
  #  # The name of the service account to use.
  #  # If not set and create is true, a name is generated using the fullname template
  #  name: ""
  #
  #podAnnotations: {}
  #
  #podSecurityContext: {}
  #  # fsGroup: 2000
  #
  #securityContext: {}
  #  # capabilities:
  #  #   drop:
  #  #   - ALL
  #  # readOnlyRootFilesystem: true
  #  # runAsNonRoot: true
  #  # runAsUser: 1000
  #
  #service:
  #  type: ClusterIP
  #  port: 80
  #
  #ingress:
  #  enabled: false
  #  className: ""
  #  annotations: {}
  #    # kubernetes.io/ingress.class: nginx
  #    # kubernetes.io/tls-acme: "true"
  #  hosts:
  #    - host: chart-example.local
  #      paths:
  #        - path: /
  #          pathType: ImplementationSpecific
  #  tls: []
  #  #  - secretName: chart-example-tls
  #  #    hosts:
  #  #      - chart-example.local
  #
  #resources: {}
  #  # We usually recommend not to specify default resources and to leave this as a conscious
  #  # choice for the user. This also increases chances charts run on environments with little
  #  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  #  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #  # limits:
  #  #   cpu: 100m
  #  #   memory: 128Mi
  #  # requests:
  #  #   cpu: 100m
  #  #   memory: 128Mi
  #
  #autoscaling:
  #  enabled: false
  #  minReplicas: 1
  #  maxReplicas: 100
  #  targetCPUUtilizationPercentage: 80
  #  # targetMemoryUtilizationPercentage: 80
  #
  #nodeSelector: {}
  #
  #tolerations: []
  #
  #affinity: {}
