kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}-dextrusui-svc
  namespace: {{ .Values.namespace | default "default" }}
spec:
  type: {{ .Values.dextrusui.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.name}}-dextrusui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
