kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace | default "default" }}
  name: efs
  annotations:
    volume.beta.kubernetes.io/storage-class: "{{ .Values.name }}-aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
