apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-wrangler-deploy
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ .Values.name }}-wrangler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-wrangler
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-wrangler
    spec:
      containers:
        - name: {{ .Values.name }}-wrangler
          image: 157557265942.dkr.ecr.ap-south-1.amazonaws.com/wrangler:cluster-0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: efs-pvc
              mountPath: "/assets"
            - name: dextrus-config-maps
              mountPath: "/home/wrangler/resources/"
              readOnly: true
          command:
            - /bin/bash
            - -c
            - |
              java -jar /home/wrangler/app.jar --spring.config.location="/home/wrangler/resources/"
      volumes:
        - name: efs-pvc
          persistentVolumeClaim:
            claimName: efs
        - name: dextrus-config-maps
          projected:
            sources:
            - configMap:
                name: {{ .Values.name }}-wrangler-app-cm
            - configMap:
                name: application-cm
            - configMap:
                name: hive-site-cm
            - configMap:
                name: metastore-site-cm

