{{- if eq (.Values.installIngressResource | toString) "yes" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: Content-Type, Authorization, Logi_Token 
    nginx.ingress.kubernetes.io/cors-allow-methods: POST, GET, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-expose-headers: X-Custom-Header
    nginx.ingress.kubernetes.io/cors-max-age: "86400"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    {{- if .Values.ingressResource.domainName }}
    {{- if eq (.Values.ingressResource.sslEnabled | toString) "yes" }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}   
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: app-ingress-resource
  namespace: {{ .Values.namespace | default "default" }}
spec:
{{- if .Values.ingressResource.domainName }}
  {{- if eq (.Values.ingressResource.sslEnabled | toString) "yes" }}
  tls:
    - hosts:
      - {{ .Values.ingressResource.domainName }}
      {{- if .Values.ingressResource.existingSecretName }}
      secretName: {{ .Values.ingressResource.existingSecretName }}
      {{- else if eq (.Values.ingressResource.createSecret | toString) "yes" }}
      secretName: {{ .Values.namespace }}-cert
      {{- else }}      
      {{- end }}
  {{- end }}        
{{- end }}
  rules:
  - http:
       paths:      
       - backend:
           service:
             name: dbexplorer-service
             port:
               number: 80
         path: /dbexplorer(/|$)(.*)
         pathType: Prefix
       - backend:
           service:
             name: systemvariables-service
             port:
               number: 80
         path: /system(/|$)(.*)
         pathType: Prefix
       - backend:
           service:
             name: dextrusweb-service
             port:
               number: 80
         path: /dweb(/|$)(.*)
         pathType: Prefix
       - backend:
           service:
             name: streaming-service
             port:
               number: 80
         path: /streaming(/|$)(.*)
         pathType: Prefix
       - backend:
           service:
             name: dextrusprod-service
             port:
               number: 80
         path: /dprod(/|$)(.*)
         pathType: Prefix        
       - backend:
           service:
             name: twitter-service
             port:
               number: 80
         path: /twitter(/|$)(.*)
         pathType: Prefix
       - backend:
           service:
             name: wrangler-service
             port:
               number: 80
         path: /wrangler(/|$)(.*)
         pathType: Prefix
    {{- if .Values.ingressResource.domainName }}
    host: {{ .Values.ingressResource.domainName }}
    {{- end }}         
{{- end }}
