apiVersion: v1
data:
  application.properties: |+
    server.port=8086
    eureka.client.register-with-eureka=false

    spring.datasource.url=jdbc:mysql://{{ .Values.rds_end_point }}:3306/dextrus_db
    spring.datasource.username=dextrus
    spring.datasource.password=Dextrus!1
    spring.datasource.driver-class-name=com.mysql.jdbc.Driver
    spring.jpa.database-platform = org.hibernate.dialect.MySQL5Dialect
    spring.jpa.generate-ddl=true
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.cloud.compatibility-verifier.enabled=false

    confluent.ip.connect=54.193.118.92
    confluent.ip.restProxy=54.193.118.92
    confluent.port.connect=8083
    confluent.port.restProxy=8082

    jwt.secret=righdata

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dextrusprod-app-prop-cm
  namespace: {{ .Values.namespace | default "default" }}
