apiVersion: v1
data:
  application-dev.yml: |
    logging:
      level:
        org.springframework.web: OFF

    server:
      port: 8086

    spring:
      h2:
        console:
          path: /h2-console
          settings:
            trace: false
            web-allow-others: false

      application:
        name: Dextrus-Prod-Applicaiton

      datasource:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://{{ .Values.rds_end_point }}:3306/dextrus_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
        username: admin
        password: changeme

      jpa:
        show-sql: true
        use_sql_comments: true

        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            show-sql: true
            use_sql_comments: true
            format_sql: true

        hibernate:
          ddl-auto: update

      servlet:
        multipart:
          max-file-size: 10GB
          max-request-size: 10GB


    jwt:
      secret: rightdata
      validity: 2 * 60 * 1000


    confluent:
      ip:
        connect: connect-svc
        restProxy: rest-svc
        bootstrap: kafka-svc
      port:
        connect: 8083
        restProxy: 8082
        bootstrap: 9092
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dextrusprod-appdev-cm
  namespace: {{ .Values.namespace | default "default" }}
