apiVersion: v1
data:
  application.yml: |
    spring:
      datasource:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://{{ .Values.rds_end_point }}:3306/dextrus_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: admin
        password: changeme


      jpa:
        show-sql: true
        use_sql_comments: true

        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
            show-sql: true
            use_sql_comments: true
            format_sql: true

        hibernate:
          ddl-auto: update

    jwt:
      secret: rightdata
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: systemvariables-cm
  namespace: {{ .Values.namespace | default "default" }}
