apiVersion: v1
data:
  application-dev.yml: |2

    logging:
      level:
        org.springframework.web: OFF

    server:
      port: 8088



    spring:
      h2:
        console:
          path: /h2-console
          settings:
            trace: false
            web-allow-others: false

      application:
        name: Twitter-Web-Applicaiton

      datasource:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://{{ .Values.rds_end_point  }}:3306/dextrus_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
        username: admin
        password: changeme

      jpa:
        show-sql: true
        use_sql_comments: true

        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            show-sql: true
            use_sql_comments: true
            format_sql: true

        hibernate:
          ddl-auto: update

      servlet:
        multipart:
          max-file-size: 10GB
          max-request-size: 10GB


    jwt:
      secret: rightdata
      validity: 2 * 60 * 1000

    deployment:
      mode: {{ .Values.deployentMode  }}

    s3:
      accessKey: {{ .Values.s3.access_key  }}
      secretKey: {{ .Values.s3.secret_key  }}
      region: {{ .Values.s3.region  }}
      bucket: {{ .Values.s3.bucket_name  }}
      endPoint: s3.{{ .Values.s3.region  }}.amazonaws.com

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: twitter-appdev-cm
  namespace: {{ .Values.namespace | default "default" }}
