---
apiVersion: v1
kind: Service
metadata:
  name: kafka-jmx-svc
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: kafka
    #  annotations:
    #    "helm.sh/hook-weight": "2"
    
spec:
  ports:
    - port: 39999
      name: jmx
  type: ClusterIP
  selector:
    app: kafka
