apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: kafka
    #  annotations:
    #    "helm.sh/hook-weight": "2"
    
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      name: broker
  selector:
    app: kafka
