---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless-svc
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: zookeeper
    #  annotations:
    #    "helm.sh/hook-weight": "1"
    
spec:
  ports:
    - port: 3888
      name: leader-election
    - port: 2888
      name: server
  clusterIP: None
  selector:
    app: zookeeper

