---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-clusterip-jmx
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: zookeeper
    #  annotations:
    #    "helm.sh/hook-weight": "1"

spec:
  ports:
    - port: 39999
      name: jmx
  type: ClusterIP
  selector:
    app: zookeeper
