{{- if eq .Values.installKafka "yes" }}

apiVersion: v1
kind: Service
metadata:
  name: connect-svc
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: connect
    netpol: kafka 
spec:
  type: ClusterIP
  ports:
    - name: connect-proxy
      port: 8083
      targetPort: 8083
  selector:
    app: connect

{{- else }}
{{- end }}
