kind: Service
apiVersion: v1
metadata:
  name: dbexplorer-service
  namespace: {{ .Values.namespace | default "default" }}
spec:
  type: {{ .Values.dbexplorer.service.type | default "ClusterIP" }}
  selector:
    app: dbexplorer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
