apiVersion: v1
kind: Service
metadata:
  name: dbexplorer-headless-service
  namespace: {{ .Values.namespace | default "default" }}
spec:
  selector:
    app: dbexplorer
  ports:
    - protocol: TCP
      port: 44103
  clusterIP: None
