kind: Service
apiVersion: v1
metadata:
  name: dextrusweb-sparkui-service
  namespace: {{ .Values.namespace | default "default" }}
spec:
  type: {{ .Values.dextrusweb.spark_service.type | default "ClusterIP" }}
  selector:
    app: dextrusweb
    netpol: kafka-communication
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4040
