kind: Service
apiVersion: v1
metadata:
  name: dextrusweb-service
  namespace: {{ .Values.namespace | default "default" }}
spec:
  type: {{ .Values.dextrusweb.service.type | default "ClusterIP" }}
  selector:
    app: dextrusweb
    netpol: kafka-communication
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
