apiVersion: v1
kind: Service
metadata:
  name: dextrusweb-headless-service
  namespace: {{ .Values.namespace | default "default" }}
spec:
  selector:
    app: dextrusweb
    netpol: kafka-communication
  ports:
    - protocol: TCP
      port: 44103
  clusterIP: None
