kind: Service
apiVersion: v1
metadata:
  name: dextrusui-service
  namespace: {{ .Values.namespace | default "default" }}
spec:
  type: {{ .Values.dextrusui.service.type | default "ClusterIP" }}
  selector:
    app: dextrusui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
