kind: Service
apiVersion: v1
metadata:
  name: dextrusprod-service
  namespace: {{ .Values.namespace | default "default" }}
spec:
  type: {{ .Values.dextrusprod.service.type | default "ClusterIP" }}
  selector:
    app: dextrusprod
    netpol: kafka-communication
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8086
