{{- if eq .Values.installKafka "yes" }}

apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: kafka
    netpol: kafka
spec:
  clusterIP: None
  ports:
    - port: 9092
      targetPort: 9092
      name: broker
  selector:
    app: kafka

{{- else }}
{{- end }}
