{{- if eq .Values.installKafka "yes" }}

apiVersion: v1
kind: Service
metadata:
  name: rest-svc
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: rest
    netpol: kafka 
spec:
  type: ClusterIP
  ports:
    - name: rest-proxy
      port: 8082
      targetPort: 8082
  selector:
    app: rest
{{- else }}
{{- end }}
