{{- if eq .Values.installKafka "yes" }}
apiVersion: v1
kind: Service
metadata:
  name: schema-registry-svc
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: schema-registry
    netpol: kafka 
spec:
  type: ClusterIP
  ports:
    - name: schema-registryistry
      port: 8081
      targetPort: 8081
  selector:
    app: schema-registry

{{- else }}
{{- end }}
