{{- if eq .Values.installKafka "yes" }}
apiVersion: v1
kind: Service
metadata:
  name: schemareg-svc
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: schemareg
    netpol: kafka 
spec:
  type: ClusterIP
  ports:
    - name: schema-registry
      port: 8081
      targetPort: 8081
  selector:
    app: schemareg

{{- else }}
{{- end }}
