apiVersion: v1
kind: Service
metadata:
  name: streaming-headless-service
  namespace: {{ .Values.namespace | default "default" }}
spec:
  selector:
    app: streaming
    netpol: kafka-communication
  ports:
    - protocol: TCP
      port: 44103
  clusterIP: None

