kind: Service
apiVersion: v1
metadata:
  name: systemvariables-service
  namespace: {{ .Values.namespace | default "default" }}
spec:
  type: {{ .Values.systemVariable.service.type | default "ClusterIP" }}
  selector:
    app: systemvariables
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
