kind: Service
apiVersion: v1
metadata:
  name: wrangler-sparkui-service
  namespace: {{ .Values.namespace | default "default" }}
spec:
  type: {{ .Values.wrangler.spark_service.type | default "ClusterIP" }}
  selector:
    app: wrangler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4040
