---
{{- if eq .Values.installKafka "yes" }}
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: zookeper
    netpol: kafka
    #  annotations:
    #    "helm.sh/hook-weight": "1"
spec:
  ports:
    - port: 2181
      name: client
  type: ClusterIP
  selector:
    app: zookeeper
{{- else }}
{{- end }}
