---
{{- if eq .Values.installKafka "yes" }}
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: zookeeper
    netpol: kafka 
spec:
  ports:
    - port: 3888
      name: leader-election
    - port: 2888
      name: server
  clusterIP: None
  selector:
    app: zookeeper
{{- else }}
{{- end }}
