{{- if eq ( .Values.enableNetworkPolicy | toString ) "yes" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dextrusui-allow-egress-dbexplorer
  namespace: {{ .Values.namespace | default "default" }}
spec:
  podSelector:
    matchLabels:
      app: dextrusui
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: dbexplorer
    ports:
    - protocol: TCP
      port: 8081
{{- end }}      
