{{- if eq ( .Values.enableNetworkPolicy | toString ) "yes" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dextrusprod-allow-ingress-dextrusui
  namespace: {{ .Values.namespace | default "default" }}
spec:
  podSelector:
    matchLabels:
      app: dextrusprod
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: dextrusui
    ports:
    - protocol: TCP
      port: 8086
  policyTypes:
  - Ingress
{{- end }}    
