{{- if eq ( .Values.enableNetworkPolicy | toString ) "yes" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dextrusweb-allow-egress-schema-registryistry
  namespace: {{ .Values.namespace | default "default" }}
spec:
  podSelector:
    matchLabels:
      app: dextrusweb
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: schema-registryistry
    ports:
    - protocol: TCP
      port: 8081
{{- end }}      
