{{- if eq ( .Values.enableNetworkPolicy | toString ) "yes" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-allow-ingress-streaming
  namespace: {{ .Values.namespace | default "default" }}
spec:
  podSelector:
    matchLabels:
      app: kafka
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: streaming
    ports:
    - protocol: TCP
      port: 9092
  policyTypes:
  - Ingress
{{- end }}    
