{{- if eq ( .Values.enableNetworkPolicy | toString ) "yes" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rest-allow-ingress-dextrusprod
  namespace: {{ .Values.namespace | default "default" }}
spec:
  podSelector:
    matchLabels:
      app: rest
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: dextrusprod
    ports:
    - protocol: TCP
      port: 8082
  policyTypes:
  - Ingress
{{- end }}    
