{{- if eq ( .Values.enableNetworkPolicy | toString ) "yes" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spark2spark
  namespace: {{ .Values.namespace | default "default" }}
spec:
  podSelector:
    matchLabels:
      spark-role: executor
  ingress:
  - from:
    - podSelector:
        matchLabels:
          spark-role: executor
  egress:
  - to:
    - podSelector:
        matchLabels:
          spark-role: executor
  policyTypes:
  - Ingress
  - Egress
{{- end }}    
