{{- if eq ( .Values.enableNetworkPolicy | toString ) "yes" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: streaming-allow-ingress-twitter
  namespace: {{ .Values.namespace | default "default" }}
spec:
  podSelector:
    matchLabels:
      app: streaming
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: twitter
    ports:
    - protocol: TCP
      port: 8081
  policyTypes:
  - Ingress
{{- end }}    
