{{- if eq ( .Values.enableNetworkPolicy | toString ) "yes" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: systemvariables-allow-ingress-streaming
  namespace: {{ .Values.namespace | default "default" }}
spec:
  podSelector:
    matchLabels:
      app: systemvariables
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: streaming
    ports:
    - protocol: TCP
      port: 8080
  policyTypes:
  - Ingress
{{- end }}    
