{{- if eq ( .Values.enableNetworkPolicy | toString ) "yes" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wrangler-allow-ingress-dextrusui
  namespace: {{ .Values.namespace | default "default" }}
spec:
  podSelector:
    matchLabels:
      app: wrangler
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: dextrusui
    ports:
    - protocol: TCP
      port: 8085
  policyTypes:
  - Ingress
{{- end }}    
