{{- if eq ( .Values.enableNetworkPolicy | toString ) "yes" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: zookeeper-allow-ingress-streaming
  namespace: {{ .Values.namespace | default "default" }}
spec:
  podSelector:
    matchLabels:
      app: zookeeper
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: streaming
    ports:
    - protocol: TCP
      port: 2181
  policyTypes:
  - Ingress

{{- end }}    
